---
title: "Regresion Logística"
author: "Yanink Neried Caro Vega y Lizbeth Naranjo Albarrán"
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 5.35 del Libro de Agresti (2015)

*The New York Times reported results of a study on the effects of AZT in
slowing the development of AIDS symptoms (February 15, 1991). Veterans
whose immune symptoms were beginning to falter after infection with HIV
were randomly assigned to receive AZT immediately or wait until their T
cells showed severe immune weakness. During the 3-year study, of those
who received AZT, 11 of 63 black subjects and 14 of 107 white subjects
developed AIDS symptoms. Of those who did not receive AZT, 12 of 55
black subjects and 32 of 113 white subjects developed AIDS symptoms. Use
model building, including checking fit and interpreting effects and
inference, to analyze these data.*

Agresti, A. (2015). *Foundations of Linear and Generalized Linear
Models*. Wiley Series in Probability and Statistics. Wiley.

Pregunta de interés:\
**¿Existe el efecto significativo del tratamiento de AZT en el
desarrollo de SIDA?**

### Datos

| Tratamiento                | Raza   | Si SIDA  | No SIDA | Total |
|----------------------------|--------|----------|---------|-------|
| Reciben AZT inmediatamente | Negra  | 11       | 52      | 63    |
|                            | Blanca | 14       | 93      | 107   |
| No reciben AZT, esperar    | Negra  | 12       | 43      | 55    |
|                            | Blanca | 32       | 81      | 113   |
| -------------------------- | ------ | -------- | ------- | ----- |
|                            |        | 69       | 269     | 338   |

### Modelo con datos NO agrupados (respuesta 0 y 1)

$$Y_i \sim Bernoulli(p_i)$$\
- $Y_i$ es el número de casos que Sí desarrollaron síntomas de SIDA.\
- Considerando que se tienen $n$ casos expuestos (Total).

```{R}
sida = c(rep(1,11),rep(0,52),rep(1,14),rep(0,93),rep(1,12),rep(0,43),rep(1,32),rep(0,81))  
tratamiento = c(rep("Recibir AZT",63+107),rep("Esperar",55+113))  
raza = c(rep("Negra",63),rep("Blanca",107),rep("Negra",55),rep("Blanca",113))  
table(sida,tratamiento,raza)
head(cbind(sida,tratamiento,raza),3)
tail(cbind(sida,tratamiento,raza),3)
length(sida)
sum(sida)
# Modelos univariados
modelo.raza <- glm(sida ~ raza, family=binomial(link="logit"))
summary(modelo.raza)
modelo.trat <- glm(sida ~ tratamiento, family=binomial(link="logit"))
summary(modelo.trat)
# Modelo multivariado
modelo2 <- glm(sida ~ tratamiento+raza, family=binomial(link="logit"))
summary(modelo2)
```

### Interpretación

Momios del Tratamiento AZT: \begin{eqnarray*}
{p_{azt} \over {1-p_{azt}}} &=& e^{\beta_0+\beta_1}  \\
{\mathbb{P}[\text{desarrollar SIDA} | Recibir AZT] \over \mathbb{P}[\text{No desarrollar SIDA} | Recibir AZT]} &=& e^{\beta_0+\beta_1}
\end{eqnarray*}

```{R}
exp(-1.01809-0.71946)   ### 0.175951   factor de proteccion (no de riesgo) 
```

indicando que entre los que Sí recibieron AZT inmediatamente, existen 17
que desarrollaron SIDA por cada 100 que no desarrollaron la enfermedad.
Todas las demás variables en su categoría de referencia.

Momios para los que No reciben AZT de inmediato (categoria de
referencia), y esperan hasta que sus células T muestren una debilidad
inmunológica grave: \begin{eqnarray*}
{p_{esperar} \over {1-p_{esperar}}} &=& e^{\beta_0}  \\
{\mathbb{P}[\text{desarrollar SIDA} | Esperar] \over \mathbb{P}[\text{No desarrollar SIDA}|Esperar]} &=& e^{\beta_0} 
\end{eqnarray*}

```{R}
exp(-1.01809)   ### 0.3612843   factor de proteccion (no de riesgo)  
```

indicando que entre los que No recibieron tratamiento inmediatamente,
existen 36 que desarrollaron SIDA por cada 100 que no desarrollaron la
enfermedad. Todas las demás variables en su categoría de referencia.

Cociente de momios (*odds ratio*): \begin{eqnarray*}
{{p_{azt} \over {1-p_{azt}}} \over {p_{esperar} \over {1-p_{esperar}}}} &=& e^{\beta_1}  
\end{eqnarray*}

```{R}
exp(-0.71946)   ### 0.4870152  ###  = 0.175951/0.3612843
```

indicando que ante el tratamiento de AZT inmediato, la posibilidad de
desarrollar SIDA es 0.48 veces más que en el caso de esperar a que sus
células T muestren una debilidad inmunológica grave. Todas las demás
variables en su categoría de referencia.

Equivale a que los odds de desarrollar SIDA ante el tratamiento de AZT
inmediato es 0.48 veces mayor (52% menor) que los odds de desarrollar
SIDA que en el caso de esperar a que sus células T muestren una
debilidad inmunológica grave.

Cociente de momios (*odds ratio*): \begin{eqnarray*}
{p_{esperar} \over {1-p_{esperar}}}}  \over {{p_{azt} \over {1-p_{azt}}}  &=& e^{-\beta_1}  
\end{eqnarray*}

```{R}
exp(0.71946)   ### 2.053324  ###  = 0.3612843/0.175951
```

Equivale a que los odds de desarrollar SIDA en el caso de esperar a que
sus células T muestren una debilidad inmunológica grave es 2.05 veces
mayor (105% mayor) que los odds de desarrollar SIDA ante el tratamiento
de AZT inmediato.

#### Sensibilidad, Especificidad y Curva ROC

```{R, out.width = "40%"}
library(AUC)
pred2 <- predict(modelo2,type="response")   ### Predecir P[Y=1]
Ypred2 <- ifelse(pred2>0.15,1,0)   ### Predecir Y, considerando como punto de corte 0.5
table(sida,Ypred2)   ### Tabla de observaciones vs. predicciones
VP <- sum(sida==1 & Ypred2==1)
VN <- sum(sida==0 & Ypred2==0)
FP <- sum(sida==0 & Ypred2==1)
FN <- sum(sida==1 & Ypred2==0)
VP/(VP+FN)   ### sensibilidad
VN/(VN+FP)   ### especificidad
sens2 <- sensitivity(pred2,factor(sida))   ### Calcula la sensibilidad
head(sens2$cutoffs)   ### puntos de corte para calcular la sensibilidad
head(sens2$measure)   ### valores de la sensibilidad
spec2 <- specificity(pred2,factor(sida))   ### Calcula la especificidad
head(spec2$cutoffs)   ### puntos de corte para calcular la especificidad
head(spec2$measure)   ### valores de la especificidad
plot(roc(pred2,factor(sida)),main="Curva ROC")
auc(roc(pred2,factor(sida)))   ### Area bajo la curva ROC
```

\newpage

### Modelo con datos agrupados

Esto se puede representar como:\
$$Y_i \sim Binomial(n_i,p_i)$$\
- $Y_i$ es el número de casos que Sí desarrollaron síntomas de SIDA.\
- Considerando que se tienen $n_i$ casos expuestos (Total).\
- Para el conjunto de características $x_i$ (recibe AZT o no, raza negra
o blanca).\
- Cuya probabilidad de presentar síntomas de SIDA es $p_i$.\
El modelo de regresión logística implica que la forma en cómo se
relaciona $p_i$ con $x_i$ es:\
$$p_i = {e^{x_i\beta} \over {1+e^{x_i\beta}}} \qquad {o} \qquad \log\left({p_i \over 1-p_i}\right)=x_i\beta$$

```{R}
sidaG = c(11,14,12,32)  
totalG = c(63,107,55,113)  
tratamientoG = factor(c("Recibir AZT","Recibir AZT","Esperar","Esperar"))  
razaG = factor(c("Negra","Blanca","Negra","Blanca"))  
modeloG <- glm(cbind(sidaG,totalG-sidaG) ~ tratamientoG+razaG, family=binomial(link="logit"))
summary(modeloG)
```
